# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, choices=[('BKE-BLVD', 'Bike Boulevard'), ('BKE-BUFF', 'Buffered Bike Lane'), ('BKE-LANE', 'Bike Lane'), ('BKE-SHRD', 'Shared Roadway or Marked Bicycle Route'), ('BKE-TRAK', 'Cycle Track'), ('OTH-CONN', 'Shared Roadway Gap Connector'), ('OTH-SWLK', 'Sidewalk'), ('OTH-XING', 'Pedestrian or Bike Overpass/underpass'), ('PTH-LOMU', 'Local Multiuse Path'), ('PTH-REMU', 'Regional Multiuse Path'), ('SHL-WIDE', 'Wide Shoulder')], max_length=255, null=True)),
                ('bike_there_classification', models.CharField(blank=True, choices=[('CA', 'Caution Area'), ('HT', 'High Traffic'), ('MT', 'Medium Traffic'), ('LT', 'Light Traffic')], max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
